// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utujsdkpxigyxhvyfoka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0dWpzZGtweGlneXhodnlmb2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTQyNTksImV4cCI6MjA4ODU3MDI1OX0.Lo8Cowq8bbfOylqth8kfyA03RHj_59RMlesIOf8Gjb0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});